### ISSUE TITLE
Alif Lam Mim

### ISSUE THREAD

**Issue by choerulafifanto** [alpancs/quranize-rs#20]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/9566566/211522556-634c1de8-d2ec-48a2-b3f9-c6a87c3d87b2.png">

ga ketemu bro

**Comment by alpancs** [comment]
diperbaiki di v0.8.0
![image](https://user-images.githubusercontent.com/4321516/213198205-70730ef4-5519-4d07-b604-01cd34c0cab1.png)
